import * as tsParser from "@typescript-eslint/parser";
import { RuleTester } from "@typescript-eslint/rule-tester";
import { afterAll, describe, it } from "vitest";

import rule from "../../src/rules/no-enum.js";

RuleTester.afterAll = afterAll;
RuleTester.describe = describe;
RuleTester.it = it;
RuleTester.itOnly = it.only;

const ruleTester = new RuleTester({
  languageOptions: {
    parser: tsParser,
  },
});

ruleTester.run("no-enum", rule, {
  valid: [
    // String-literal union — the prescribed pattern.
    { code: 'type Status = "active" | "inactive";' },
    // `as const` object — also prescribed.
    {
      code: "const Status = { Active: 'active', Inactive: 'inactive' } as const;",
    },
    // A file with `@generated` near the top opts out.
    {
      code: "// @generated by openapi-typescript\nenum Status { A, B }",
    },
    // Files under a `generated/` segment opt out by default.
    {
      code: "enum Status { A, B }",
      filename: "/repo/src/generated/api.ts",
    },
    // `.gen.ts` suffix opts out by default.
    {
      code: "enum Status { A, B }",
      filename: "/repo/src/api.gen.ts",
    },
  ],
  invalid: [
    {
      code: "enum Status { Active, Inactive }",
      errors: [{ messageId: "noEnum" }],
    },
    {
      code: 'enum Color { Red = "red", Blue = "blue" }',
      errors: [{ messageId: "noEnum" }],
    },
    {
      code: "const enum Direction { Up, Down, Left, Right }",
      errors: [{ messageId: "noEnum" }],
    },
    // Honors a custom ignoreFiles glob.
    {
      code: "enum Status { Active }",
      filename: "/repo/src/normal.ts",
      options: [{ ignoreFiles: ["**/codegen/**"] }],
      errors: [{ messageId: "noEnum" }],
    },
  ],
});
